### ISSUE TITLE
Libpng 1.6.17 in defaults is incompatible with 1.6.21 in conda-foge

### ISSUE THREAD

**Issue by 183amir** [conda-forge/libpng-feedstock#3]
This may not be an issue of this feedstock but I am reporting it here.
Till now all packages are pinned with version `1.6*` of the `libpng` but sometimes `conda` decides to pull `libpng-1.6.17-0` from `defaults` instead of `libpng-1.6.21-1` from `conda-forge`. When that happens I face [this error](https://travis-ci.org/conda-forge/bob.ip.optflow.liu-feedstock/jobs/132107891#L740) in [this pull](https://github.com/conda-forge/bob.ip.optflow.liu-feedstock/pull/2):

``` python
import bob.io.image

  File "/Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/bob/io/image/__init__.py", line 4, in <module>

    from . import _library

ImportError: dlopen(/Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/bob/io/image/_library.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libpng16.16.dylib

  Referenced from: /Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/bob/io/image/_library.cpython-35m-darwin.so

  Reason: Incompatible library version: _library.cpython-35m-darwin.so requires version 38.0.0 or later, but libpng16.16.dylib provides version 34.0.0
```

The problem here is `bob.io.image` is built with `libpng-1.6.21-1` but here `libpng-1.6.17-0` is being pulled when it is used in `bob.ip.optflow.liu`.
How do you think we could prevent this? Should we pin `libpng` to `1.6.21*`?

**Comment by ocefpaf** [comment]
Indeed that is a problem and I already tried to change the pinning. At the time @pelson thought that pinning to the minor version was too much. Maybe we should re-visit that decision.

**Comment by 183amir** [comment]
I think the best solution is pinning to the minor version.

**Comment by pelson** [comment]
I can't find the thread now, but @jakirkham and I have discussed minor version pinning. In general it isn't needed but around 1.6.17 and 1.6.21 a binary incompatibility seems to have been introduced. I agree we need to be more specific with our pinning, but it maybe that `>=1.6.21,<1.7` would be more appropriate.

**Comment by jankatins** [comment]
If it is just a problem that `bob.io.image` requires a newer version (which I suspect because otherwise the PNG devs would have changed the filename to `libpng17.17.dylib`), then IMO that package should just be changed to `>=<lowest verison which works>`. 

If it is really an incompatibility, IMO the easiest change would be to add a API compatibility version to the package name, so that both png version can be installed at the same time (the runtime libs already have different filenames...). `>=1.6.21,<1.7` style is IMO also going to break if there is a new incompatibility in the 1.6 branch. -> Make the (binary) package name the complete SONAME of the lib: `libpng16.16.dylib` -> `libpng16`.

Pinning to minor will IMO a real pain when one wants to install packages which are build against different versions.

**Comment by 183amir** [comment]
It is really an incompatibility. `bob.io.image` does not need anything special.

**Comment by jankatins** [comment]
can you run `ldd -d /Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/bob/io/image/_library.cpython-35m-darwin.so` or `otool -l /Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/bob/io/image/_library.cpython-35m-darwin.so` (I got that form a help page, so maybe that could be the wrong command; No windows packages for bob.io.image :-( )? 

I'm not sure if this error is just the result of a `I got compiled with 38.0.0 and don't want anything less` or really a missing symbol...

**Comment by jankatins** [comment]
After digging in a bit more in #4 and a bit of googleing (e.g. [this](http://stackoverflow.com/questions/10342046/in-xcode-how-do-i-link-a-dynamic-library-libcurl-so-that-the-app-also-works-o?lq=1) and [this](http://docstore.mik.ua/orelly/unix3/mac/ch05_04.htm)), I'm even more convinced that this is simply a problem of versions, because the SONAME is still the same (=`libpng16` = ABI compatibility = old apps can link against newer versions of the lib) 

 IMO in this case this happened:
- the bob.io.image recipe was "constructed" when libpng was older -> everything works
- a new libpng is introduced which is ABI and API compatible: old apps can link against newer version of the lib (=SONAME is kept at `libpng16`), btu it increases the "compatibility version" (see [here](http://docstore.mik.ua/orelly/unix3/mac/ch05_04.htm)) so apps which are build against newer versions expect the new lib version to make sure that they don't accidentally miss a symbol which was introduced in the newer version of the lib 
- now the recipe is rebuild and the build pulls in the newer version of the lib. The binary relationship is tighter due to the cautiousness of the linker/app but the recipe still contains the old loose dependency.
- now conda thinks that it can use an older libpng, but the binary complains...

So IMO the fix is to tighten the build and binary dependency in `bob.io.image` package in the newer version in conda-forge.

I'm not sure if there is a way to link against a "lower" compatibility version of the library: This suggest there might:

> You can link against a particular version of a library by including the appropriate option for cc, such as -lMagick.5.0.42.
> [from http://docstore.mik.ua/orelly/unix3/mac/ch05_04.htm]

This line suggests that it compiles against the whole name, version included: https://github.com/bioidiap/bob.io.image/blob/master/setup.py#L318

**Comment by 183amir** [comment]
@janschulz here is the output of `ldd -d`:

```
env LD_LIBRARY_PATH=python2.7/site-packages/bob/io/base:python2.7/site-packages/bob/core ldd -d python2.7/site-packages/bob/io/image/_library.so
    linux-vdso.so.1 (0x00007fff96b53000)
    libbob_io_base.so => python2.7/site-packages/bob/io/base/libbob_io_base.so (0x00007f1e75a8b000)
    libbob_core.so => python2.7/site-packages/bob/core/libbob_core.so (0x00007f1e75862000)
    libboost_system.so.1.60.0 => /usr/lib/libboost_system.so.1.60.0 (0x00007f1e75624000)
    libboost_filesystem.so.1.60.0 => /usr/lib/libboost_filesystem.so.1.60.0 (0x00007f1e7540b000)
    libpng16.so.16 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/image/../../../../../libpng16.so.16 (0x00007f1e751c9000)
    libblitz.so.0 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/image/../../../../../libblitz.so.0 (0x00007f1e74fc5000)
    libjpeg.so.9 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/image/../../../../../libjpeg.so.9 (0x00007f1e74d89000)
    libtiff.so.5 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/image/../../../../../libtiff.so.5 (0x00007f1e74b15000)
    libgif.so.7 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/image/../../../../../libgif.so.7 (0x00007f1e7490d000)
    libpython2.7.so.1.0 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/image/../../../../../libpython2.7.so.1.0 (0x00007f1e74526000)
    libstdc++.so.6 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/image/../../../../../libstdc++.so.6 (0x00007f1e74169000)
    libm.so.6 => /usr/lib/libm.so.6 (0x00007f1e73e65000)
    libgcc_s.so.1 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/image/../../../../../libgcc_s.so.1 (0x00007f1e73c4e000)
    libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f1e73a30000)
    libc.so.6 => /usr/lib/libc.so.6 (0x00007f1e7368f000)
    libhdf5.so.10 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/base/../../../../../libhdf5.so.10 (0x00007f1e731af000)
    libboost_iostreams.so.1.60.0 => /usr/lib/libboost_iostreams.so.1.60.0 (0x00007f1e72f96000)
    librt.so.1 => /usr/lib/librt.so.1 (0x00007f1e72d8d000)
    libz.so.1 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/image/../../../../.././libz.so.1 (0x00007f1e72b77000)
    liblzma.so.5 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/io/image/../../../../.././liblzma.so.5 (0x00007f1e72954000)
    libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f1e72750000)
    libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f1e7254d000)
    /usr/lib64/ld-linux-x86-64.so.2 (0x000056388b951000)
    libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f1e7233c000)
```

As for Windows packages, there are some dependencies that need to be built for Windows first. We will be glad if someone adds Windows builds to the `bob` stack.
And as for your last comment, I could not understand it properly mainly because I'm really tired. So what are you proposing exactly?

**Comment by 183amir** [comment]
Also, Have you seen my pull here: https://github.com/conda-forge/bob.ip.optflow.liu-feedstock/pull/5 and its build log here: https://travis-ci.org/conda-forge/bob.ip.optflow.liu-feedstock/builds/132385238

**Comment by jankatins** [comment]
@183amir I think you need the output from a osx system

**Comment by pelson** [comment]
Thanks for doing this @janschulz!

**Comment by pelson** [comment]
Sorry just posted here accidentally. (too many open tabs)

**Comment by ocefpaf** [comment]
@183amir I believe this can be closed, right?

**Comment by 183amir** [comment]
Yes.
